import type { DatasourceConfig } from '../types/datasource';

export const DATASOURCE_LIBRARY: DatasourceConfig[] = [
  {
    type: 'mysql',
    label: 'MySQL',
    icon: 'Database',
    color: '#4479A1',
    defaultConfig: {
      host: 'localhost',
      port: 3306,
      database: '',
      username: '',
      password: '',
      charset: 'utf8mb4',
    },
    configFields: [
      { name: 'host', label: '主机地址', type: 'text', required: true, placeholder: 'localhost' },
      { name: 'port', label: '端口', type: 'number', required: true, defaultValue: 3306 },
      { name: 'database', label: '数据库名', type: 'text', required: true, placeholder: 'mydb' },
      { name: 'username', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
      { name: 'charset', label: '字符集', type: 'text', defaultValue: 'utf8mb4' },
    ],
  },
  {
    type: 'postgresql',
    label: 'PostgreSQL',
    icon: 'Database',
    color: '#336791',
    defaultConfig: {
      host: 'localhost',
      port: 5432,
      database: '',
      username: '',
      password: '',
      ssl: false,
    },
    configFields: [
      { name: 'host', label: '主机地址', type: 'text', required: true, placeholder: 'localhost' },
      { name: 'port', label: '端口', type: 'number', required: true, defaultValue: 5432 },
      { name: 'database', label: '数据库名', type: 'text', required: true, placeholder: 'mydb' },
      { name: 'username', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
      { name: 'ssl', label: '启用SSL', type: 'checkbox' },
    ],
  },
  {
    type: 'mongodb',
    label: 'MongoDB',
    icon: 'Database',
    color: '#47A248',
    defaultConfig: {
      connectionString: '',
      database: '',
    },
    configFields: [
      { name: 'connectionString', label: '连接字符串', type: 'text', required: true, placeholder: 'mongodb://localhost:27017' },
      { name: 'database', label: '数据库名', type: 'text', required: true },
    ],
  },
  {
    type: 'redis',
    label: 'Redis',
    icon: 'Database',
    color: '#DC382D',
    defaultConfig: {
      host: 'localhost',
      port: 6379,
      password: '',
      db: 0,
    },
    configFields: [
      { name: 'host', label: '主机地址', type: 'text', required: true, placeholder: 'localhost' },
      { name: 'port', label: '端口', type: 'number', required: true, defaultValue: 6379 },
      { name: 'password', label: '密码', type: 'password' },
      { name: 'db', label: '数据库编号', type: 'number', defaultValue: 0 },
    ],
  },
  {
    type: 'elasticsearch',
    label: 'Elasticsearch',
    icon: 'Search',
    color: '#005571',
    defaultConfig: {
      node: 'http://localhost:9200',
      username: '',
      password: '',
    },
    configFields: [
      { name: 'node', label: '节点地址', type: 'text', required: true, placeholder: 'http://localhost:9200' },
      { name: 'username', label: '用户名', type: 'text' },
      { name: 'password', label: '密码', type: 'password' },
    ],
  },
  {
    type: 'http',
    label: 'HTTP API',
    icon: 'Globe',
    color: '#3b82f6',
    defaultConfig: {
      baseUrl: '',
      headers: {},
      timeout: 30000,
    },
    configFields: [
      { name: 'baseUrl', label: '基础URL', type: 'text', required: true, placeholder: 'https://api.example.com' },
      { name: 'timeout', label: '超时时间(ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    type: 'oracle',
    label: 'Oracle',
    icon: 'Database',
    color: '#F80000',
    defaultConfig: {
      host: 'localhost',
      port: 1521,
      serviceName: '',
      username: '',
      password: '',
    },
    configFields: [
      { name: 'host', label: '主机地址', type: 'text', required: true, placeholder: 'localhost' },
      { name: 'port', label: '端口', type: 'number', required: true, defaultValue: 1521 },
      { name: 'serviceName', label: '服务名', type: 'text', required: true },
      { name: 'username', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'sqlserver',
    label: 'SQL Server',
    icon: 'Database',
    color: '#CC2927',
    defaultConfig: {
      server: 'localhost',
      port: 1433,
      database: '',
      username: '',
      password: '',
      encrypt: false,
    },
    configFields: [
      { name: 'server', label: '服务器地址', type: 'text', required: true, placeholder: 'localhost' },
      { name: 'port', label: '端口', type: 'number', required: true, defaultValue: 1433 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'username', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
      { name: 'encrypt', label: '启用加密', type: 'checkbox' },
    ],
  },
];
