import type { NodeConfig } from '../types';

export const NODE_LIBRARY: NodeConfig[] = [
  {
    type: 'trigger',
    label: '触发器',
    icon: 'Zap',
    color: '#f59e0b',
    bgColor: '#fffbeb',
    description: '工作流的起始点',
    defaultParams: { event: '' },
    inputs: [],
    outputs: ['output'],
  },
  {
    type: 'action',
    label: '操作',
    icon: 'MousePointerClick',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    description: '执行特定操作',
    defaultParams: { action: '' },
    inputs: ['input'],
    outputs: ['output'],
  },
  {
    type: 'condition',
    label: '条件判断',
    icon: 'GitBranch',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    description: '根据条件分支',
    defaultParams: { condition: '' },
    inputs: ['input'],
    outputs: ['true', 'false'],
  },
  {
    type: 'transform',
    label: '数据转换',
    icon: 'ArrowRightLeft',
    color: '#14b8a6',
    bgColor: '#f0fdfa',
    description: '转换数据格式',
    defaultParams: { mapping: '' },
    inputs: ['input'],
    outputs: ['output'],
  },
  {
    type: 'api',
    label: 'API请求',
    icon: 'Globe',
    color: '#10b981',
    bgColor: '#ecfdf5',
    description: '调用外部API',
    defaultParams: { url: '', method: 'GET' },
    inputs: ['input'],
    outputs: ['success', 'error'],
  },
  {
    type: 'database',
    label: '数据库',
    icon: 'Database',
    color: '#f97316',
    bgColor: '#fff7ed',
    description: '数据库操作',
    defaultParams: { datasourceId: '', query: '' },
    inputs: ['input'],
    outputs: ['output'],
  },
  {
    type: 'notification',
    label: '通知',
    icon: 'Bell',
    color: '#ec4899',
    bgColor: '#fdf2f8',
    description: '发送通知消息',
    defaultParams: { message: '', channel: '' },
    inputs: ['input'],
    outputs: ['output'],
  },
  {
    type: 'output',
    label: '输出',
    icon: 'CheckCircle',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    description: '工作流结束',
    defaultParams: {},
    inputs: ['input'],
    outputs: [],
  },
];
